---
- name: set config
  template: >
    src=squid.conf
    dest=/etc/squid3/squid.conf
    owner=root
    group=root
    owner=0644

- name: restart squid3
  service:
    name=squid3
    state=restarted
