---
- name: install apt-transport-https
  apt:
    name: apt-transport-https
    update_cache: yes
- name: set gpg.key
  apt_key:
    url: https://packagecloud.io/gpg.key
- name: set source.list
  apt_repository:
    repo: 'deb https://packagecloud.io/Hypriot/Schatzkiste/debian/ wheezy main'
- name: apt-get install docker-hypriot
  apt: >
    name={{ item }}
    update_cache=yes
  with_items:
    - docker-hypriot
    - docker-compose
    - python-dev
    - python-pip
- name: easy_install
  easy_install:
    name: pip
    state: latest
- name: pip install docker-py
  pip:
    name: "{{ item }}"
  with_items:
    - docker-py
    - docker-compose
- name: enable service docker
  service:
    name: docker
    enabled: yes
