---
- name: install lirc
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - lirc
    - apache2
    - php5
    - git

- name: /etc/lirc/hardware.conf
  template:
    src: hardware.conf
    dest: /etc/lirc/hardware.conf
    owner: root
    group: root
    mode: 0644

- name: /boot/config.txt
  template:
    src: config.txt
    dest: /boot/config.txt
    owner: root
    group: root
    mode: 0644

- name: ~/lirc_cut.py
  template:
    src: lirc_cut.py
    dest: /var/www/html/lirc_cut.py
    owner: root
    group: root
    mode: 0664

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=300
  sudo: false
