---
- name: docker deploy tensorflow
  docker_service:
    project_name: tensowflow
    definition:
      version: '2'
      services:
        tensorflow:
          image: tensorflow/tensorflow
          ports:
            - 8888:8888
