---
- apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python-dev
    - python-pip
    - libappindicator1

- copy:
    src: google-chrome-stable_current_amd64.deb
    dest: /tmp/

- apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
  
- pip:
    name: selenium

- get_url:
    url: https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
    dest: /opt/
