---
- name: docker deploy mattermost
  docker_service:
    project_name: mattermost
    definition:
      version: '2'
      services:
        db:
          build: "{{ playbook_dir }}/roles/mattermost/mattermost-docker/db/"
          volumes:
            - /srv/docker/mattermost/db/var/lib/postgresql/data:/var/lib/postgresql/data
            - /etc/localtime:/etc/localtime:ro
        app:
          build: "{{ playbook_dir }}/roles/mattermost/mattermost-docker/app"
          volumes:
            - "/srv/docker/gitlab/postgresql:/var/lib/postgresql:Z"
          environment:
            - DB_USER=gitlab
            - DB_PASS=password
            - DB_NAME=gitlabhq_production
            - DB_EXTENSION=pg_trgm
          links:
            - db:db
          volumes:
            - /srv/docker/mattermost/app/config:/mattermost/config:rw
            - /srv/docker/mattermost/app/data:/mattermost/data:rw
            - /etc/localtime:/etc/localtime:ro
        web:
          build: "{{ playbook_dir }}/roles/mattermost/mattermost-docker/web"
          ports:
            - "80:80"
            - "443:443"
          volumes:
            - /srv/docker/mattermost/web/cert:/cert:ro
            - /etc/localtime:/etc/localtime:ro
          environment:
            - MATTERMOST_ENABLE_SSL=false
            - PLATFORM_PORT_80_TCP_PORT=80
          links:
            - app:app
