---
- name: update kernel to 3.19+
  apt: >
    name="linux-generic-lts-vivid"
    update_cache=yes
    cache_valid_time=86400
  environment:
    DEBIAN_FRONTEND: "noninteractive"
  register: update_kernel

- name: turn off intel_rapl autoload
  lineinfile: >
    dest="/etc/modprobe.d/blacklist.conf"
    line="blacklist intel_rapl"

- name: reboot for kernel update
  command: reboot
  async: 0
  poll: 0
  ignore_errors: yes
  when: update_kernel|changed

- name: wait for reboot
  local_action:
    module: wait_for
      host="{{ inventory_hostname }}"
      port=22
      delay=1
      timeout=300
  when: update_kernel|changed
