---
- name: apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install python-opencv libopencv-dev motion
  apt:
    name={{ item }}
  with_items:
    - python-opencv
    - libopencv-dev
    - motion

- name: set /etc/motion/motion.conf
  copy:
    src: ./motion.conf
    dest: /etc/motion/motion.conf
    owner: root
    group: root
    mode: 0644
 
- name: install slacker
  pip:
    name={{ item }}
  with_items:
    - slacker

- name: create directory plant_factory
  file:
    path={{ item }}
    state=directory
    mode=0755
  with_items:
    - ~/plant_factory
    - ~/plant_factory/snapshot

- name: set plant script
  copy:
    src: script
    dest: ~/plant_factory/
    owner: root
    group: root
    mode: 0755

